"""Generate a reproducible environment from a capture: a pinned lockfile + a Dockerfile.

Uses the *used* distributions (what the run actually imported, versioned) so the generated environment
installs exactly what the experiment needed — not the whole original machine. The command is taken from
the capture, with the interpreter normalized to the image's ``python``.

Honest limit (baseline capture): this reconstructs the *Python* environment. System libraries an
extension wheel linked against (a specific BLAS, a CUDA runtime) are not visible without the eBPF deep
mode, so a generated image can still miss a native dependency. That gap is exactly what Track 2 closes.
"""
from __future__ import annotations

from ..models import CaptureRecord, GeneratedEnvironment


def _python_tag(version: str | None) -> str:
    """'3.12.3' -> '3.12' for the base image tag; default to a recent minor if unknown."""
    if version:
        parts = version.split(".")
        if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
            return f"{parts[0]}.{parts[1]}"
    return "3.12"


def _requirements_lock(rec: CaptureRecord) -> str:
    lines = ["# Generated by darnit-reproducibility from an Amber capture.",
             "# Pinned to the distributions the run actually used."]
    for d in sorted(rec.python_env.used_distributions, key=lambda x: (x.get("name") or "").lower()):
        name, ver = d.get("name"), d.get("version")
        if name and ver:
            lines.append(f"{name}=={ver}")
    return "\n".join(lines) + "\n"


def _run_command(rec: CaptureRecord) -> list[str]:
    """The captured command with the interpreter path normalized to the image's ``python``."""
    cmd = list(rec.command.cmd) or ["python", "experiment.py"]
    if cmd and ("python" in cmd[0].rsplit("/", 1)[-1]):
        cmd[0] = "python"
    return cmd


_SO_TO_APT = {
    "libopenblas": "libopenblas0", "liblapack": "liblapack3", "libgomp": "libgomp1",
    "libgfortran": "libgfortran5", "libstdc++": "libstdc++6", "libquadmath": "libquadmath0",
}


def _native_apt_hints(rec: CaptureRecord) -> list[str]:
    """apt packages suggested by native shared objects loaded outside the Python import system.

    Baseline capture can't prove a wheel bundles its native lib, so these are emitted as a commented
    hint (deep eBPF mode would confirm which are actually needed)."""
    deep = rec.ebpf_file_access or {}
    pkgs: set[str] = set()
    for so in deep.get("shared_objects", []):
        if so.get("in_python_modules"):
            continue
        name = so.get("path", "").rsplit("/", 1)[-1]
        for prefix, apt in _SO_TO_APT.items():
            if name.startswith(prefix):
                pkgs.add(apt)
    return sorted(pkgs)


def _dockerfile(rec: CaptureRecord) -> str:
    tag = _python_tag(rec.python_env.version)
    cmd = _run_command(rec)
    cmd_json = "[" + ", ".join(f'"{c}"' for c in cmd) + "]"
    commit = rec.repo.commit or "unknown"
    num = rec.numerical or {}
    hashseed = num.get("pythonhashseed") or "0"
    tz = num.get("timezone") or "UTC"
    # Pin BLAS/OpenMP thread caps to what was captured (default 1) — thread count changes float results.
    threads = dict(num.get("thread_env") or {})
    for k in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
        threads.setdefault(k, "1")
    thread_lines = "\n".join(f"ENV {k}={v}" for k, v in sorted(threads.items()))
    apt = _native_apt_hints(rec)
    apt_hint = (f"\n# Native libraries observed loaded outside the Python import system (deep trace).\n"
                f"# Uncomment if the pip wheels don't already bundle them:\n"
                f"# RUN apt-get update && apt-get install -y {' '.join(apt)} && rm -rf /var/lib/apt/lists/*\n"
                if apt else "")
    return f"""# Auto-generated by darnit-reproducibility (Amber) to reproduce a captured run.
# Source commit: {commit}
FROM python:{tag}-slim
{apt_hint}

# Reproducibility knobs (from the capture)
ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONHASHSEED={hashseed} \\
    SOURCE_DATE_EPOCH=0 \\
    TZ={tz}
{thread_lines}

WORKDIR /work

# Pinned Python dependencies the run actually used
COPY requirements.lock /tmp/requirements.lock
RUN pip install --no-cache-dir -r /tmp/requirements.lock

# Experiment source (checkout {commit} before building this image)
COPY . /work

CMD {cmd_json}
"""


def _conda_env(rec: CaptureRecord) -> str:
    ver = rec.python_env.version or "3.12"
    lines = ["# Generated by darnit-reproducibility from an Amber capture.",
             "name: reproduced", "channels:", "  - conda-forge", "dependencies:",
             f"  - python={ver}", "  - pip", "  - pip:"]
    for d in sorted(rec.python_env.used_distributions, key=lambda x: (x.get("name") or "").lower()):
        if d.get("name") and d.get("version"):
            lines.append(f"    - {d['name']}=={d['version']}")
    return "\n".join(lines) + "\n"


def generate(rec: CaptureRecord, target: str = "docker") -> GeneratedEnvironment:
    """Generate an environment definition. ``target`` in {'docker', 'requirements', 'conda'}."""
    lock = _requirements_lock(rec)
    notes = []
    if not rec.python_env.used_distributions:
        notes.append("no used distributions captured — lockfile is empty; re-run capture?")
    notes.append("baseline capture: native/system libraries are not included (needs eBPF deep mode)")

    if target == "requirements":
        return GeneratedEnvironment(target="requirements",
                                    files={"requirements.lock": lock}, notes=notes)
    if target == "conda":
        return GeneratedEnvironment(target="conda",
                                    files={"environment.yml": _conda_env(rec)}, notes=notes)
    return GeneratedEnvironment(
        target="docker",
        files={"Dockerfile": _dockerfile(rec), "requirements.lock": lock},
        notes=notes,
    )


def main(argv: list[str] | None = None) -> int:
    import argparse
    from pathlib import Path

    from ..ingest import witness as ing

    p = argparse.ArgumentParser(prog="amber-generate",
                                description="Generate a reproducible environment from an Amber capture.")
    p.add_argument("bundle")
    p.add_argument("--pylibs", default=None)
    p.add_argument("--target", choices=["docker", "requirements", "conda"], default="docker")
    p.add_argument("--out-dir", default=".")
    args = p.parse_args(argv)

    rec = ing.load(args.bundle, args.pylibs)
    env = generate(rec, args.target)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for name, content in env.files.items():
        (out / name).write_text(content)
        print(f"wrote {out / name}")
    for n in env.notes:
        print(f"note: {n}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
